# Generated by Django 4.2.3 on 2023-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="product/product_cover"),
                ),
                ("active", models.BooleanField(default=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
